name: coo
channels:
  - defaults
  - conda-forge
  - bioconda
  - r

dependencies:
  # Python dependencies
  - python=3.8
  - postgresql=14
  
  # R dependencies
  - r-base=4.1.1
  - r-seurat=4.0.3
  - r-archr=1.0.1
  - r-tidyverse=1.3.1 # includes ggplot2, dplyr, stringr, tibble
  - r-data.table=1.14.0
  - r-optparse=1.7.1
  - r-rtracklayer=1.52.0
  - r-readxl=1.3.1
  - r-tidytext=0.3.0
  - r-magrittr=2.0.1
  - r-rcolorbrewer=1.1_2

  # pip packages 
  - pip:
    - optuna==3.3.0
    - scikit-learn==1.3.0

