name: coo
channels:
  - defaults
  - conda-forge
  - bioconda
  - r

dependencies:
  # General utilities
  - pip=23.2.1
  # Python dependencies
  - python=3.8
  - postgresql=14

  # R dependencies
  - r-base=4.1.0
  - r-tidyverse=1.3.2
  - r-data.table=1.14.8
  - r-optparse=1.7.3
  - r-rcolorbrewer=1.1.3

  # pip packages 
  - pip:
    - optuna==3.3.0
    - scikit-learn==1.3.0
    - xgboost==1.7.4
    - pyreadr==0.4.9
