name: coo
channels:
  - defaults
  - conda-forge
  - bioconda
  - r

dependencies:
  # General utilities
  - pip=21.2.4

  # Python dependencies
  - python=3.8
  - postgresql=14

  # R dependencies
  - r-base=4.0.3
  - r-seurat=3.2.2
  - r-tidyverse=1.3.0
  - r-data.table=1.13.2
  - r-optparse=1.6.6
  - r-readxl=1.3.1
  - r-rcolorbrewer=1.1.2

  # pip packages 
  - pip:
    - optuna==3.3.0
    - scikit-learn==1.3.0
    - xgboost==1.7.6
    - pyreadr==0.4.9
