name: coosim
channels:
  - conda-forge 
  - defaults
  - bioconda
  - r

dependencies:
  # General utilities
  - pip=23.2.1
  # Python dependencies
  - python=3.8.18
  #- postgresql=14.5
  - pkg-config=0.29.2
  # R dependencies
  - r-base=4.3.1
  - libiconv=1.17
  - libxml2=2.12.6
  #- r-tidyverse=2.0.0
  #- r-data.table=1.14.8
  #- r-optparse=1.7.3
  #- r-rcolorbrewer=1.1.3
  #- r-irkernel==1.3.2
  #- r-viridis==0.6.3
  #- r-tidytext==0.4.1
  # pip packages 
  - pip:
    - openpyxl==3.1.2
    - optuna==3.3.0
    - scikit-learn==1.3.0
    - xgboost==1.7.4
    - notebook==6.0.3
    - pyreadr==0.4.9
    - natsort==8.4.0
    - psycopg2==2.9.7
    - statsmodels==0.13.5
    - scanpy==1.9.6
    - gdown==5.1.0
  # bash
  - entrez-direct=16.2
